# Generated by Django 5.2 on 2025-04-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicioceci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='fecha_creation',
            field=models.DateField(null=True),
        ),
    ]
